[package]
name = "procgen"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.30"
anyhow = "1.0.56"
nalgebra = "0.30.1"
num-traits = "0.2.14"

[dependencies.tokio]
version = "1.17"
features = ["full"]

[dependencies.serde]
version = "1.0"
features = ["derive"]